# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
pool:
  Default
steps:
- task: CmdLine@2
  name: "Pre_Command_Check"
  inputs:
    script: |
      echo Commands are running
      echo Successfully...
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '*/surefire-reports/TEST-.xml'
    allowBrokenSymlinks: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/target'
    Contents: '**.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Milestone'
    publishLocation: 'Container'